### ISSUE TITLE
[Konquest] Task #12767 for Konquest v1.3.0 generated an exception

### ISSUE THREAD

**Issue by Alpha5959** [Rumsfield/konquest#179]
```console
java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
        at com.github.rumsfield.konquest.hook.DiscordSrvHook.getLinkMessage(DiscordSrvHook.java:80) ~[Konquest-1.3.0.jar:?]
        at com.github.rumsfield.konquest.listener.PlayerListener.lambda$onPlayerJoin$0(PlayerListener.java:169) ~[Konquest-1.3.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.20.4.jar:git-Paper-381]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-381]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

It's a issue with DiscordSRV. Whenever a players try to join the server the error pops up.

**Comment by Rumsfield** [comment]
Thanks for reporting this, I'll look into fixing it.
